CREATE TABLE IF NOT EXISTS DNS_LOG_LINES (
  LOG_TIME     BIGINT       NOT NULL,
  QUERY_TYPE   VARCHAR(255) NULL,
  QUERY_DOMAIN VARCHAR(255) NULL,
  QUERY_TARGET VARCHAR(255) NULL
);

-- CREATE INDEX IF NOT EXISTS DNS_LOG_LINES_IDX USING BTREON DNS_LOG_LINES(LOG_TIME, QUERY_TYPE, QUERY_DOMAIN, QUERY_TARGET);