DROP TABLE IF EXISTS DNS_LOG_LINES_TEST;

CREATE TABLE IF NOT EXISTS DNS_LOG_LINES_TEST  (
  LOG_TIME    	int(11) NOT NULL,
  QUERY_TYPE  	varchar(255) NULL,
  QUERY_DOMAIN	varchar(255) NULL,
  QUERY_TARGET	varchar(255) NULL
);