CREATE TABLE IF NOT EXISTS DNS_LOG_LINES (
  LOG_TIME     BIGINT       NOT NULL,
  QUERY_TYPE   VARCHAR(255) NULL,
  QUERY_DOMAIN VARCHAR(255) NULL,
  QUERY_TARGET VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS DNS_IGNORE (
  IGNORE_ID     INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IGNORE_DOMAIN VARCHAR(255) NOT NULL
);

-- Enable on production servers, if needed
-- CREATE INDEX IF NOT EXISTS DNS_LOG_LINES_IDX USING BTREE ON DNS_LOG_LINES(LOG_TIME, QUERY_TYPE, QUERY_DOMAIN, QUERY_TARGET);