DROP TABLE IF EXISTS DNS_LOG_LINES;

DROP TABLE IF EXISTS DNS_IGNORE;

CREATE TABLE IF NOT EXISTS DNS_LOG_LINES (
  LOG_TIME     BIGINT       NOT NULL,
  QUERY_TYPE   VARCHAR(255) NULL,
  QUERY_DOMAIN VARCHAR(255) NULL,
  QUERY_TARGET VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS DNS_IGNORE (
  IGNORE_ID     INT          NOT NULL,
  IGNORE_DOMAIN VARCHAR(255) NOT NULL
);