DROP TABLE IF EXISTS DNS_LOG_LINES;

CREATE TABLE IF NOT EXISTS DNS_LOG_LINES  (
  LOG_TIME    	BIGINT NOT NULL,
  QUERY_TYPE  	varchar(255) NULL,
  QUERY_DOMAIN	varchar(255) NULL,
  QUERY_TARGET	varchar(255) NULL
);